@startuml

' verhindere Probleme mit gewinkelten Krähenfüßen
skinparam linetype ortho

entity "plants" as plant {
  *plant_id : nummer <<generiert,PK>>
  --
  *name : text <<unique>>
  *species_name : text
  *image : text <<URL>>
  *added : datum <<durch DB>>
  *watering_interval : nummer <<in Tagen>>
  *watering_interval_offset : nummer <<in Tagen>>
}

entity "activities" as log {
  *id : nummer <<generiert,PK>>
  *plant_id : nummer <<FK>>
  --
  *type : nummer <<0=Water, 1=Repot>>
  *date : datum <<durch DB>>
}

log }o..|| plant

@enduml