services:
  frontend:
    image: ghcr.io/quadcoredevelopment/plantmanager_frontend:latest
    ports: 
      - 8000:8000
    environment:
      # IMPORTANT: Change this URL!
      - BACKEND_URL=http://YOURSERVER:8001

  backend:
    image: ghcr.io/quadcoredevelopment/plantmanager_backend:latest
    ports: 
      - 8001:8001
    environment:
      - LOG_SQLITE_QUERIES=false # set to "true" (lowercase) to enable query logging
      - LOG_HTTP_QUERIES=false   # set to "true" (lowercase) to enable HTTP request logging
    volumes:
      - db_vol:/home/node/app/db
      - images_vol:/home/node/app/public/images/plants

volumes:
  db_vol:
  images_vol: